import type { Categoria, Producto } from "./types"

export const categorias: Categoria[] = [
  {
    id: 1,
    nombre: "Running",
    slug: "running",
    imagen: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 2,
    nombre: "Fútbol",
    slug: "futbol",
    imagen: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 3,
    nombre: "Baloncesto",
    slug: "baloncesto",
    imagen: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 4,
    nombre: "Fitness",
    slug: "fitness",
    imagen: "/placeholder.svg?height=200&width=300",
  },
]

export const productosDestacados: Producto[] = [
  {
    id: 1,
    nombre: "Nike Air Zoom Pegasus 38",
    slug: "nike-air-zoom-pegasus-38",
    descripcion: "Zapatillas de running con amortiguación reactiva para tus entrenamientos diarios.",
    precio: 120,
    descuento: 10,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Running",
    colores: ["Negro", "Blanco", "Azul"],
    tallas: [39, 40, 41, 42, 43, 44, 45],
    destacado: true,
  },
  {
    id: 2,
    nombre: "Adidas Ultraboost 22",
    slug: "adidas-ultraboost-22",
    descripcion: "Máxima amortiguación y retorno de energía para corredores exigentes.",
    precio: 180,
    descuento: 0,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Running",
    colores: ["Negro", "Gris", "Rojo"],
    tallas: [39, 40, 41, 42, 43, 44],
    destacado: true,
  },
  {
    id: 3,
    nombre: "Nike Tiempo Legend 9 Elite",
    slug: "nike-tiempo-legend-9-elite",
    descripcion: "Botas de fútbol de piel premium para un control excepcional del balón.",
    precio: 230,
    descuento: 15,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Fútbol",
    colores: ["Negro", "Blanco"],
    tallas: [39, 40, 41, 42, 43, 44, 45],
    destacado: true,
  },
  {
    id: 4,
    nombre: "Adidas Predator Edge",
    slug: "adidas-predator-edge",
    descripcion: "Botas de fútbol con tecnología de control y precisión para jugadores creativos.",
    precio: 280,
    descuento: 0,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Fútbol",
    colores: ["Rojo", "Negro", "Azul"],
    tallas: [39, 40, 41, 42, 43, 44],
    destacado: true,
  },
  {
    id: 5,
    nombre: "Nike LeBron 19",
    slug: "nike-lebron-19",
    descripcion: "Zapatillas de baloncesto con amortiguación Max Air y Zoom Air para un rendimiento explosivo.",
    precio: 200,
    descuento: 0,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Baloncesto",
    colores: ["Negro", "Blanco", "Rojo"],
    tallas: [40, 41, 42, 43, 44, 45, 46],
    destacado: true,
  },
  {
    id: 6,
    nombre: "Under Armour HOVR Apex 3",
    slug: "under-armour-hovr-apex-3",
    descripcion: "Zapatillas de entrenamiento versátiles para todo tipo de ejercicios en el gimnasio.",
    precio: 140,
    descuento: 20,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Fitness",
    colores: ["Negro", "Gris"],
    tallas: [39, 40, 41, 42, 43, 44, 45],
    destacado: true,
  },
  {
    id: 7,
    nombre: "Puma Deviate Nitro 2",
    slug: "puma-deviate-nitro-2",
    descripcion: "Zapatillas de running con placa de carbono para máxima propulsión y velocidad.",
    precio: 160,
    descuento: 0,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Running",
    colores: ["Negro", "Amarillo", "Azul"],
    tallas: [39, 40, 41, 42, 43, 44],
    destacado: true,
  },
  {
    id: 8,
    nombre: "Adidas Dame 8",
    slug: "adidas-dame-8",
    descripcion: "Zapatillas de baloncesto ligeras y con gran tracción para jugadores rápidos.",
    precio: 120,
    descuento: 0,
    imagen: "/placeholder.svg?height=200&width=200",
    imagenSecundaria: "/placeholder.svg?height=200&width=200&text=Vista+Lateral",
    categoria: "Baloncesto",
    colores: ["Negro", "Rojo", "Blanco"],
    tallas: [40, 41, 42, 43, 44, 45],
    destacado: true,
  },
]
